name: Documentation

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - published

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0

    - name: Setup Mamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: false

    - name: Build environment
      run: |
        micromamba create --name TEST python=3 pip --file requirements-dev.txt --channel conda-forge
        micromamba activate TEST
        python -m pip install -e .

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(python setup.py --version)

    - name: Build documentation
      run: |
        set -e
        micromamba activate TEST
        pushd doc
        make clean html linkcheck
        popd

    - name: Deploy
      if: github.event_name == 'release' || github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/_build/html
