name: Tests

on:
  pull_request:
  push:
    branches: [master]

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
         environment-file: false
 
      - name: Python ${{ matrix.python-version }}
        run: |
          micromamba create --name TEST python=${{ matrix.python-version }} pip --file requirements-dev.txt --channel conda-forge
          micromamba activate TEST
          python -m pip install -e .
      - name: test
        run: |
          micromamba activate TEST
          coverage run -m pytest -vrsx test.py

      - name: coverage
        run: |
          micromamba activate TEST
          coverage report -m
          codecov
  
